### ISSUE TITLE
ImportError: cannot import name 'secure_filename' from 'werkzeug when using "excalibur initdb"

### ISSUE THREAD

**Issue by xubiuit** [camelot-dev/excalibur#104]
Hi guys,

I faced the issue when trying `excalibur initdb` with the package which installed via pip.
After checked, I change this line 
https://github.com/camelot-dev/excalibur/blob/395b9ef2627e53a160ed8eef87a523971cab7694/excalibur/www/views.py#L10
to `from werkzeug.utils import secure_filename` and reinstall via git clone repo in my localhost. Everything seems okay after that.

Please check to consider to update the source code and let me know if I did something wrong.

Thanks and regards,
Binh Nguyen

**Comment by vinayak-mehta** [comment]
This shouldn't be an issue with the latest release.

**Comment by ninja-lab** [comment]
I had to make this change today. I use anaconda on Windows 10, and had followed directions.
