### ISSUE TITLE
Open Excalibur in default browser

### ISSUE THREAD

**Issue by arky** [camelot-dev/excalibur#109]
Please open a browser window with Excalibur on startup. This is most common usability feature that would really nice to have.  

This could be implemented using [click.launch](https://click.palletsprojects.com/en/7.x/api/#click.launch) or [webbrowser](https://docs.python.org/3/library/webbrowser.html) module.

**Comment by vinayak-mehta** [comment]
This is a good idea! Let me create a PR for this.
