### ISSUE TITLE
[Flavor] - Selecting flavor while extracting table which requires to process background. 

### ISSUE THREAD

**Issue by Akhurana01** [camelot-dev/excalibur#112]
I have a pdf which has multiple tables having some cells with margins having colored background and some having no margin at all, only having the background color difference. While selecting the flavor as lattice or stream the alignment of the extracted text is getting disturbed a lot in case of extracting without margin cell values from tables. I even tried the same with process_background = True which is not solving the problem. 

Is there any way to resolve the issue?

**Comment by vinayak-mehta** [comment]
I can't help without looking at an image of what you're describing. You can try selecting a table area manually and see if that improves the output.

**Comment by Akhurana01** [comment]
I've sent an email to you. Thanks!
