### ISSUE TITLE
Processing PDF - error message 

### ISSUE THREAD

**Issue by sandeepraizada** [camelot-dev/excalibur#13]
I am on ubuntu 14.04 and installed excalibur-py using pip. while processing the following pdf (this is also used in camilot-py) and works well... the system returns the following message - 

ERROR:root:'Table' object has no attribute '_bbox'
Traceback (most recent call last):
File "/home/sandeep/anaconda3/lib/python3.6/site-packages/excalibur/tasks.py", line 96, in split
x1, y1, x2, y2 = tables[0]._bbox
AttributeError: 'Table' object has no attribute '_bbox'
Refresh does not change anything... if i click on excalibur then i get this msg back
"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
[background_lines.pdf](https://github.com/camelot-dev/excalibur/files/2558537/background_lines.pdf)

pdf file used is attached

**Comment by vinayak-mehta** [comment]
@sandeepraizada What Camelot version are you using? Can you install the latest version and tell me if that fixes this error?

**Comment by sandeepraizada** [comment]
Thanks Vinayak - the version is 0.3.1

**Comment by vinayak-mehta** [comment]
@sandeepraizada You need to be on Camelot version 0.3.2, which is the latest one and this should be fixed.

**Comment by sandeepraizada** [comment]
How do I do it because conda install does not take it to that version
