### ISSUE TITLE
Internal Server Error can't Download data

### ISSUE THREAD

**Issue by kyuzh** [camelot-dev/excalibur#158]
![image](https://user-images.githubusercontent.com/62187465/170294337-5c9629e2-5e38-4df6-b49e-34e0ce63ec1a.png)

**Comment by kkin1995** [comment]
Facing the same issue on macOS Monterey 12.4 with camelot version 8.9.0 and excalibur version 0.4.3.

The error message in the terminal shown is:
```
TypeError: send_from_directory() missing 1 required positional argument: 'path'
```

The error is thrown from the file:
```
excalibur/www/views.py
```

**Comment by graykimbrough** [comment]
I am seeing the same issue on macOS Monterey 12.4 with camelot 8.9.0 and excalibur 0.4.3. I receive this error when I click "Download" in either Safari or Chrome, no matter what file format I select. Here is the full traceback:

> [2022-06-16 09:01:49,261] ERROR in app: Exception on /download [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
>   File "/usr/local/lib/python3.9/site-packages/excalibur/www/views.py", line 265, in download
>     return send_from_directory(
> TypeError: send_from_directory() missing 1 required positional argument: 'path'

**Comment by kyuzh** [comment]
look here https://stackoverflow.com/questions/67591467/flask-shows-typeerror-send-from-directory-missing-1-required-positional-argum.

Just replace filename by path at line 262 in views.py.
![image](https://user-images.githubusercontent.com/62187465/174563680-b7a77cf8-ed9a-465d-8054-6103314ff20b.png)
