### ISSUE TITLE
data extracted in 2nd,3rd... page is not aligned properly as in 1st page. 

### ISSUE THREAD

**Issue by Jackblackpearl** [camelot-dev/excalibur#19]
When there are 3 pages in the PDF table on the first page is extracted and aligned properly but the in 2nd-page data is not aligned properly. Can you please let us know what needs to be modified. 

import Camelot
tables = camelot.read_pdf("D:\\drive-download-20180907T081608Z-001\\047238.pdf", flavor ='stream', pages='1-end')
tables
tables[0].df
tables.export("C:\\Users\\fooo.htm", f='html', compress=True)
![2018](https://user-images.githubusercontent.com/45002614/48413241-23085400-e76d-11e8-83ff-e4186644edf1.jpg)

**Comment by vinayak-mehta** [comment]
@Jackblackpearl Can you post a link to the PDF so that I can reproduce this? Also, this looks like a Camelot issue and not an Excalibur one.
