### ISSUE TITLE
Add user defined excalibur.cfg and PDFS_FOLDER

### ISSUE THREAD

**Issue by vinayak-mehta** [camelot-dev/excalibur#3]

**Comment by pqrth** [comment]
@vinayak-mehta, could you please elaborate on the following:
1. Which configurations do we plan to include in *excalibur.cfg*?
2. What will be the purpose of `PDFS_FOLDER` (I suppose it's an environment variable)?

**Comment by vinayak-mehta** [comment]
PDFS_FOLDER can't be user defined as of now, since it is needed to be inside the static folder to serve PNG files.
