### ISSUE TITLE
Support listening on all interfaces

### ISSUE THREAD

**Issue by williamjacksn** [camelot-dev/excalibur#30]
As far as I can tell, Excalibur listens on 127.0.0.1 and that can't be changed.

I am attempting to create a Docker container for Excalibur and I would like to have the web server listen on all interfaces to make it work.

I am not completely familiar with the code base, but I accomplished this myself by adding a "web_server_host" value to the [webserver] section of the config file, and changing the call to `app.run()` in `cli.py`:

```python
app.run(host=conf.get('webserver', 'web_server_host'), use_reloader=False)
```

Is this a change you would be interested in adding to the project?

**Comment by vinayak-mehta** [comment]
Yes, it would be awesome to add this, since it makes Excalibur more configurable! Would you be interested in submitting a PR?
