### ISSUE TITLE
Excalibur python error

### ISSUE THREAD

**Issue by madhavchunky1** [camelot-dev/excalibur#36]
When I downloaded the extracted file , I got result like below mentioned . How to get the actual value ?
(cid:40)(cid:90)(cid:3)(cid:86)(cid:85)(cid:3)(cid:91)(cid:79)

**Comment by vinayak-mehta** [comment]
Hey, this is a problem in the PDF file itself. It wasn't generated correctly at source most probably.

**Comment by vinayak-mehta** [comment]
OCR can usually help you get the text out if your PDF uses some standard fonts.
