### ISSUE TITLE
GhostscriptNotFound: Please make sure that Ghostscript is installed and available on the PATH environment variable

### ISSUE THREAD

**Issue by majestique** [camelot-dev/excalibur#37]
OS: Windows 10

After downloading excalibur, I had to download/install ghostscript (this should be stated in instructions).

After installing ghostscript, the PATH needs to be set. After setting PATH, the error still exists:
![image](https://user-images.githubusercontent.com/19336285/50655246-63ea4100-0f44-11e9-93db-ae2bd46b32bc.png)

PATH set: C:\Program Files\gs\gs9.26\bin\gswin64c.exe (I've restarted)

**Comment by vinayak-mehta** [comment]
Sorry for leaving that out, I'll add it to the README and docs.

I would recommend doing [this check](https://camelot-py.readthedocs.io/en/master/user/install-deps.html#for-ghostscript) to see if ghostscript is on the PATH variable or not. After Camelot 0.7.0, the dependency on ghostscript to be on the PATH won't be necessary.

**Comment by majestique** [comment]
Once path is set to(restart): "C:\Program Files\gs\gs9.26\bin\" it should work

**Comment by henrysouchien** [comment]
hi - I am trying to set the PATH sorry if this is dumb question - how do i set this variable or what is the name? I keep getting this error message

**Comment by rokmokorel** [comment]
> hi - I am trying to set the PATH sorry if this is dumb question - how do i set this variable or what is the name? I keep getting this error message

@henrysouchien took me a while. You should find PATH environment variable, then click edit. Then you can add "C:\Program Files\gs\gs9.26\bin" to the environment variable. You will need to restart after.

**Comment by henrysouchien** [comment]
Thank you so much!! I will try it out
