### ISSUE TITLE
Please wait while the pages are converted to images. Refresh again in some time

### ISSUE THREAD

**Issue by wujunke** [camelot-dev/excalibur#41]
![2019-01-08 1 41 23](https://user-images.githubusercontent.com/13659481/50811842-32f67b80-134b-11e9-9904-90d2d4e4de6a.png)

**Comment by ntota** [comment]
I am also facing same issue. Uploaded files are displaying under Files link but this Refresh page is not showing any results.

**Comment by cedricprunier** [comment]
I have also the same error...

**Comment by vinayak-mehta** [comment]
Looks like a bug, let me look into this. Can you also post a link to the PDF file? It will help me reproduce the issue.

**Comment by vinayak-mehta** [comment]
This is fixed now, please install the latest version v0.4.2.

**Comment by vm-asd2015** [comment]
I have just installed Excalibur via pip and face the same issue.

Excalibur --version returns: 0.4.2.

**Comment by RIYADAS** [comment]
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr. I am getting this issue. what could be the problem

**Comment by vm-asd2015** [comment]
@RIYADAS : Have a look at issue #43 and PR #45.

**Comment by yuanwu-bujin** [comment]
> This is fixed now, please install the latest version v0.4.2.


> This is fixed now, please install the latest version v0.4.2.
i use v0.4.2 also notice "refresh"

![捕获](https://user-images.githubusercontent.com/52151426/64419410-6f8f9800-d0cf-11e9-9862-3fe1234c002e.JPG)

**Comment by vasantvohra** [comment]
> This is fixed now, please install the latest version v0.4.2.
**Not fixed yet. :(**
![excalibur](https://user-images.githubusercontent.com/20479333/66808691-61902b00-ef49-11e9-9f8e-10df0e1306ac.PNG)
![excalibur bug](https://user-images.githubusercontent.com/20479333/66808692-6228c180-ef49-11e9-9a2e-666ba177c8ed.PNG)
![image](https://user-images.githubusercontent.com/20479333/66808746-7f5d9000-ef49-11e9-92ae-ac3217f1a7d2.png)
Does it works well on linux system?

**Comment by tnli** [comment]
Hello! 
I have this exact same problem with version 0.4.3 in Windows 10.

The processing page refreshes while nothing else happens.

**Comment by MahimaBarot** [comment]
> Hello!
> I have this exact same problem with version 0.4.3 in Windows 10.
> 
> The processing page refreshes while nothing else happens.
> 
> Exactly as in the above post.

facing same issue

**Comment by chenster** [comment]
It seems this project is dead

**Comment by jaycatsby** [comment]
> It seems this project is dead

It looks like it :( stuck on perpetually refreshing processing page on Windows.

**Comment by nijawa-ma** [comment]
Dang, what a shame. Looked like a great tool.
