### ISSUE TITLE
GhostScript error only for lattice when run through command line

### ISSUE THREAD

**Issue by Ishaan94** [camelot-dev/excalibur#58]
This is my code:

**import camelot
import pandas as pd
import string

class CommandLine:
    def __init__(self):
        tables=camelot.read_pdf(filepath="C:\\Users\\Ikhanna\\OneDrive - STEPSTONE GROUP LP\\Documents\\PortCo Ari\\Adam\\Q1.2018.CAB.FS.Rpt.Orion Euro RE IV.pdf", pages="1")
if __name__ == '__main__':
    app = CommandLine()**

This runs fine when I run in Jupyter notebook but when I convert this file to a .ipynb or .py and run through cmd it throws the error **RuntimeError: Please make sure that Ghostscript is installed**. It doesn't give this error if I use the stream flavour. I am not sure why this is happening

**Comment by vinayak-mehta** [comment]
Camelot is not able to find ghostscript on your PATH. Please read the docs to see how you can do that.
