### ISSUE TITLE
Error on Windows: OSError: exception: access violation writing 0x0967BC48 while running python-Excalibur code

### ISSUE THREAD

**Issue by swaraj20** [camelot-dev/excalibur#59]
camelot Excalibur thow an oserror:access violation writing 0x0967BC48
os - Windows 10
python version - 3.7

below is the output screen 
* Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [02/Jul/2019 19:03:54] "GET /files HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2019 19:04:10] "POST /files HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2019 19:04:10] "GET /workspaces/59f1c984-31fa-4ade-b944-770072f82827 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2019 19:04:19] "GET /workspaces/59f1c984-31fa-4ade-b944-770072f82827 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2019 19:04:20] "GET /static/favicon.ico HTTP/1.1" 200 -
ERROR:root:exception: access violation writing 0x0967BC48
Traceback (most recent call last):
  File "c:\users\comp7\appdata\local\programs\python\python37-32\lib\site-packages\excalibur\tasks.py", line 44, in split
    with Ghostscript(*gs_call, stdout=null) as gs:
  File "c:\users\comp7\appdata\local\programs\python\python37-32\lib\site-packages\camelot\ext\ghostscript\__init__.py", line 93, in Ghostscript
    stderr=kwargs.get('stderr', None))
  File "c:\users\comp7\appdata\local\programs\python\python37-32\lib\site-packages\camelot\ext\ghostscript\__init__.py", line 39, in __init__
    rc = gs.init_with_args(instance, args)
  **File "c:\users\comp7\appdata\local\programs\python\python37-32\lib\site-packages\camelot\ext\ghostscript\_gsprint.py", line 167, in init_with_args
    rc = libgs.gsapi_init_with_args(instance, len(argv), c_argv)
OSError: exception: access violation writing 0x0967BC48**

![excal](https://user-images.githubusercontent.com/52457527/60518728-b80d8c80-9cff-11e9-955b-2ba76012a60e.png)

**Comment by ac-asks** [comment]
I am getting the same error on a Mac. Also Python 3.7. I'm running it locally via flask run. Any help would be appreciated!


127.0.0.1 - - [09/Jul/2019 09:14:01] "GET /static/css/vendor/jquery-ui.structure.min.css HTTP/1.1" 200 -
127.0.0.1 - - [09/Jul/2019 09:14:01] "GET /static/css/workspace.css HTTP/1.1" 200 -
127.0.0.1 - - [09/Jul/2019 09:14:01] "GET /static/js/vendor/jquery.selectareas.min.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Jul/2019 09:14:01] "GET /static/js/workspace.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Jul/2019 09:14:01] "GET /static/js/vendor/jquery-ui.min.js HTTP/1.1" 200 -
GPL Ghostscript 9.27: Unrecoverable error, exit code 1
ERROR:root:-100
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/excalibur/tasks.py", line 44, in split
    with Ghostscript(*gs_call, stdout=null) as gs:
  File "/usr/local/lib/python3.7/site-packages/camelot/ext/ghostscript/__init__.py", line 93, in Ghostscript
    stderr=kwargs.get('stderr', None))
  File "/usr/local/lib/python3.7/site-packages/camelot/ext/ghostscript/__init__.py", line 39, in __init__
    rc = gs.init_with_args(instance, args)
  File "/usr/local/lib/python3.7/site-packages/camelot/ext/ghostscript/_gsprint.py", line 169, in init_with_args
    raise GhostscriptError(rc)
camelot.ext.ghostscript._gsprint.GhostscriptError: -100

**Comment by andyg101** [comment]
I am also experiencing this issue

**Comment by SevlaMare** [comment]
get this error with fresh virtual env, in python 2.7 too.

**Comment by smondragon-intera** [comment]
Had the same error. Fixed by installing camelot from repo as mentioned here https://github.com/atlanhq/camelot/issues/262

**Comment by vinayak-mehta** [comment]
Please try the @smondragon-intera's solution and reopen if you still face the issue.

**Comment by shrutipb** [comment]
Hi i am also facing the same issue WindowsError: exception: access violation writing 0x00000080
i am using
window 10 64 bit
python 2.7 32 bit 
gs 32 bit
tried all solutions

**Comment by shubhangisingh2ey** [comment]
Facing the same issue even after installing camelot from repo as mentioned above
