### ISSUE TITLE
Failure when "all" or 1-end is selected

### ISSUE THREAD

**Issue by VAnthonyrajah** [camelot-dev/excalibur#65]
Excalibur struggles on large pdfs (20pgs or more) when I indicate the "all" or "1-end" options.
I get the following warning:
UserWarning: No tables found on page-144 [lattice.py:399]
UserWarning: No tables found on page-144 [stream.py:447]
UserWarning: No tables found in table area 1 [stream.py:361]
UserWarning: No tables found in table area 1 [stream.py:361]
UserWarning: No tables found in table area 2 [stream.py:361]

However if I manually select the pages it works fine. Is there a way to solve this?

**Comment by vinayak-mehta** [comment]
Is it because tables in your PDF lie on different parts of the page and the single table area you've selected doesn't work.

**Comment by VAnthonyrajah** [comment]
> Is it because tables in your PDF lie on different parts of the page and the single table area you've selected doesn't work.

Hi @vinayak-mehta  I believe this happens when one of the pages in the pdf dont have tables. Then the whole process fails. Does that make sense?

**Comment by vinayak-mehta** [comment]
Please post the settings you used (you can get it from the Rules view) or with a screenshot, along with the PDF.
