### ISSUE TITLE
ERROR:root:'charmap' codec can't encode character '\ued6f' in position 350: char acter maps to <undefined>

### ISSUE THREAD

**Issue by randomstability** [camelot-dev/excalibur#66]
I am unable to share the pdf that is causing this issue.  I would like to know what I can do to bypass this error.  
Even if it means dropping the "offending char".  Getting some of the data is better than getting none of the data.
I'd be ecstatic if this is a PEBKAC issue,  so please don't discount that.

Using the latest download of excaliber and Python 3.7.3 (I think).  Only using the webui to do this.  Don't think I could handle coding it, without some hand holding.

This is happening on several pages of a very large pdf (700+ pages).  But not all of them.  So the file can be parsed.  Just not the important portion, which is most of the file.

I DID just realize that it is creating some of the output files  (excel, csv, and json), but not html.  Since I on'y really need the csv or excel,  I might be good.   Will keep pushing on the remainder of the file (its slow to handle 100 pages at a time)

```
127.0.0.1 - - [05/Aug/2019 16:55:09] "GET /jobs/fbfeb974-5f3d-4991-b26c-98356064
0de5 HTTP/1.1" 200 -
ERROR:root:'charmap' codec can't encode character '\ued6f' in position 350: char
acter maps to <undefined>
Traceback (most recent call last):
  File "excalibur\executors\sequential_executor.py", line 12, in execute_command

  File "subprocess.py", line 336, in check_call
  File "subprocess.py", line 317, in call
  File "subprocess.py", line 769, in __init__
  File "subprocess.py", line 1172, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "excalibur\tasks.py", line 161, in extract
  File "lib\site-packages\camelot\core.py", line 479, in export
  File "lib\site-packages\camelot\core.py", line 437, in _write_file
  File "lib\site-packages\camelot\core.py", line 394, in to_html
  File "C:\Python37\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\ued6f' in position
350: character maps to <undefined>
```

**Comment by vinayak-mehta** [comment]
Looks like a problem with the PDF.

**Comment by randomstability** [comment]
Have you considered that maybe this invalid character is a technique to prevent copying of the data/pdf?  It seems like it would be really helpful to simply skip parsing a problematic character, and notify the user of errors seen, indicating the output may be invalid due to invalid content in the source PDF.

**Comment by vinayak-mehta** [comment]
That seems like a good idea, I'll add it to the backlog.
