### ISSUE TITLE
Excalibur's data directory is created in HOME

### ISSUE THREAD

**Issue by akx** [camelot-dev/excalibur#67]
I consider it bad form for Excalibur to create a user-visible folder in the home folder (`/Users/akx/excalibur` on my Mac, for instance).

It'd be better to use e.g. [`appdirs`](https://pypi.org/project/appdirs/) to figure out the "user data" directory, and create the Excalibur directory there.

**Comment by vinayak-mehta** [comment]
You can set `excalibur_home` to change the default data directory.

**Comment by akx** [comment]
Where would that configuration file be placed?

**Comment by vinayak-mehta** [comment]
My bad, you can set `EXCALIBUR_HOME` in your environment before installing the package to fix this. https://github.com/camelot-dev/excalibur/blob/master/excalibur/configuration.py#L92
