### ISSUE TITLE
Command not found error on ubuntu

### ISSUE THREAD

**Issue by Sanket-Shirode** [camelot-dev/excalibur#68]
unable to use camelot and excalibur commands from commandline in ubuntu

**Comment by siddharthshah3030** [comment]
@Sanket-Shirode 
facing the same issue, 
what's the fix?

**Comment by Sanket-Shirode** [comment]
Used the packaged excalibur application 
and started it using the executable present in the application

**Comment by KosmetikOn** [comment]
could you please elaborate on what is the packaged excalibur app and how to get it?
thanks!

**Comment by vinayak-mehta** [comment]
Please use `python -m excalibur`.
