### ISSUE TITLE
Add tk along with ghostscript in the "using pip" section of installation

### ISSUE THREAD

**Issue by vinayak-mehta** [camelot-dev/excalibur#72]

**Comment by geekypandey** [comment]
Can I please take this issue? 
The link attached with it should be same as in the documentation in installing dependencies for camleot-py docs? https://wiki.python.org/moin/TkInter <-- This link?

**Comment by vinayak-mehta** [comment]
Sorry for the super late reply. Please take this up if you're still interested.
