### ISSUE TITLE
werkzeug.utils not werkzeug

### ISSUE THREAD

**Issue by jrthorstensen** [camelot-dev/excalibur#90]
excalibur would not start on my linux Fedora 29 system.  here was the message:

.local/bin/excalibur
Traceback (most recent call last):
  File ".local/bin/excalibur", line 5, in <module>
    from excalibur.cli import cli
  File "/home/thorsten/.local/lib/python3.6/site-packages/excalibur/cli.py", line 12, in <module>
    from .www.app import create_app
  File "/home/thorsten/.local/lib/python3.6/site-packages/excalibur/www/app.py", line 7, in <module>
    from .views import views
  File "/home/thorsten/.local/lib/python3.6/site-packages/excalibur/www/views.py", line 10, in <module>
    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename'

After some googling I fixed it myself by editing line 10 in views.py to read 

from werkzeug.utils import secure_filename

This seems like a very simple issue to fix.

After that, the program worked brilliantly.  I found it on 

https://hackernoon.com/an-open-source-science-tool-to-extract-tables-from-pdfs-into-excels-3ed3cc7f22e1

John Thorstensen

**Comment by Axo-Fv** [comment]
Thanks. Worked for me.

**Comment by SiddhantArya** [comment]
I am also having a similar issue on Mac. 
Can you help me set this up so that there are no dependancy issue?

**Comment by LuxGiammi** [comment]
@SiddhantArya simply edit the file views.py (in your case `/Users/siddhantarya/opt/anaconda3/lib/python3.7/site-packages/excalibur/www/views.py`) and replace the line `from werkzeug import secure_filename` with `from werkzeug.utils import secure_filename`

**Comment by vinayak-mehta** [comment]
Please install the latest version using `pip install --upgrade excalibur-py`.
