### ISSUE TITLE
Install is broken

### ISSUE THREAD

**Issue by guysbryant** [camelot-dev/excalibur#91]
I cloned the repo and ran pip install . and this is the output:
<img width="932" alt="Screen Shot 2020-02-23 at 18 02 34" src="https://user-images.githubusercontent.com/15893869/75121912-adc14980-5666-11ea-9a03-fdb25cf1166d.png">

As you can see, when I tried to run excalibur initdb, zsh couldn't find the excalibur command.
Bash didn't do any better and restarting the terminal didn't make a difference either.
I am on macos catalina

**Comment by vinayak-mehta** [comment]
Please install the latest version using `pip install --upgrade excalibur-py` and try using the CLI using `python -m excalibur --help`.
