### ISSUE TITLE
ImportError: cannot import name 'secure_filename' after `excalibur initdb`

### ISSUE THREAD

**Issue by belisards** [camelot-dev/excalibur#95]
I can't start the database after running the command: _excalibur initdb_

I get this error:

~$ excalibur initdb
Creating new Excalibur configuration file in: /home/localhost/excalibur/excalibur.cfg
Traceback (most recent call last):
  File "/home/localhost/.local/bin/excalibur", line 5, in <module>
    from excalibur.cli import cli
  File "/home/localhost/.local/lib/python3.6/site-packages/excalibur/cli.py", line 12, in <module>
    from .www.app import create_app
  File "/home/localhost/.local/lib/python3.6/site-packages/excalibur/www/app.py", line 7, in <module>
    from .views import views
  File "/home/localhost/.local/lib/python3.6/site-packages/excalibur/www/views.py", line 10, in <module>
    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename'

It seems that the library mentioned is already installed.

~$ pip3 install werkzeug
Requirement already satisfied: werkzeug in ./.local/lib/python3.6/site-packages (1.0.0)
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Any tip?

**Comment by fffact** [comment]
same here.
found [this issue](https://github.com/pallets/werkzeug/issues/1714) which seems related.
will investigate further.

**Comment by arky** [comment]
@fffact  @belisards Looks like camelot-dev doesn't work with latest werkzeug version. Try using previous version with: 

`pip install werkzeug==0.16.1

Let me know if this works for you. 
`

**Comment by hirensuraiya** [comment]
Was having the same issue. Fix worked for me. Thanks @arky!

**Comment by arky** [comment]
@vinayak-mehta @dimitern  Am assuming there are some PRs that could resolve this problem? 

https://github.com/camelot-dev/excalibur/pull/92

**Comment by vinayak-mehta** [comment]
Hello everyone. Yes @arky, I haven't been getting time to work on these projects. But I'll check out the PRs, merge them and create a release today.

**Comment by fffact** [comment]
> @fffact @belisards Looks like camelot-dev/excalibur doesn't work with latest werkzeug version. Try using previous version with:
> 
> `pip install werkzeug==0.16.1
> 
> Let me know if this works for you.
> `

@arky yes it works. thanks!

**Comment by vinayak-mehta** [comment]
Please install the latest version using `pip install --upgrade excalibur-py`.

**Comment by arky** [comment]
Thanks @vinayak-mehta for quick fix. 
BTW Am trying to reach to excalibur team. Do you have IRC or slack? Please let me know. Thanks!

**Comment by vinayak-mehta** [comment]
@arky There's a gitter channel https://gitter.im/camelot-dev/Lobby
