### ISSUE TITLE
Excalibur Windows 32-bit builds 

### ISSUE THREAD

**Issue by arky** [camelot-dev/excalibur#99]
Excalibur windows (0.4.0) fails to run on 32 bit Windows 7 operating systems.  Tested using latest [windows release](https://github.com/camelot-dev/excalibur/releases/download/v0.4.0/excalibur-win-v0.4.0.zip)

**Comment by arky** [comment]
@vinayak-mehta I'll be happy to fix this issue with little guidance from your end.

**Comment by arky** [comment]
@vinayak-mehta This issue could be resolved by adopting github actions build workflow https://github.com/camelot-dev/excalibur/pull/107

**Comment by vinayak-mehta** [comment]
Thanks for the PR! Checking it out.

**Comment by vinayak-mehta** [comment]
> Excalibur windows (0.4.0) fails to run on 32 bit Windows 7 operating systems. Tested using latest windows release

@arky What is the error that it fails with?

**Comment by vinayak-mehta** [comment]
I've triggered a workflow run, are you able to see it? https://github.com/camelot-dev/excalibur/actions/runs/171797774

**Comment by vinayak-mehta** [comment]
Oh no, I think the artifacts aren't being zipped correctly.

**Comment by vinayak-mehta** [comment]
@arky Can you try one of the Windows package from here: https://github.com/camelot-dev/excalibur/actions/runs/171875604 and see if you face any issues? I tried the Linux one and can confirm that it works.

**Comment by arky** [comment]
@vinayak-mehta I'll test Windows 32 and 64 builds shortly.

**Comment by arky** [comment]
@vinayak-mehta I guess we need to ensure the python 32bit is running by default for 32bit builds to work properly?

MS Windows 10 64bit : Test Successful 
MS Windows 7 32bit: Test Failed 
```
.\excalibur-windows-latest-ia32.exe 
Program 'excalibur-windows-latest-ia32.exe' failed to execute: This version of %1 is not compatible with the version of
 Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit
) version of the program, and then contact the software publisher
At line:1 char:36
+ .\excalibur-windows-latest-ia32.exe <<<<  2>&1 > 
At line:1 char:1
+  <<<< .\excalibur-windows-latest-ia32.exe
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed


```

**Comment by arky** [comment]
@vinayak-mehta  64bit python is used on windows-32bit builds  https://github.com/camelot-dev/excalibur/runs/879409166?check_suite_focus=true

 ```
Set up Python 3.8
architecture: x64
Run actions/setup-python@v1
  with:
    python-version: 3.8
    architecture: x64
Successfully setup CPython (3.8.3)
```

**Comment by vinayak-mehta** [comment]
Let me add `x86` Python for 32-bit Windows in the build matrix.

**Comment by vinayak-mehta** [comment]
@arky Can you check the 32 bit version from here https://github.com/camelot-dev/excalibur/actions/runs/172556185

**Comment by arky** [comment]
Excalibur launches on windows 32 bit machines. Resolved with https://github.com/camelot-dev/excalibur/commit/dac340f6a46398ef59958f29cb7ff86651814e75

Thanks @vinayak-mehta

**Comment by vinayak-mehta** [comment]
@arky Thanks for your help with the PR and testing the packages! I'll create a release now.
